/* tslint:disable */
/* eslint-disable */
/**
 * Accounts API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: aira3t@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { ErrorResponse } from '../models';
// @ts-ignore
import { GeocodeReverseResult } from '../models';
/**
 * GeoApi - axios parameter creator
 * @export
 */
export const GeoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get location address information
         * @summary Get location address information
         * @param {string} authorization Bearer
         * @param {number} lat latitude
         * @param {number} lon longitude
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1GeoReverseGet: async (authorization: string, lat: number, lon: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('v1GeoReverseGet', 'authorization', authorization)
            // verify required parameter 'lat' is not null or undefined
            assertParamExists('v1GeoReverseGet', 'lat', lat)
            // verify required parameter 'lon' is not null or undefined
            assertParamExists('v1GeoReverseGet', 'lon', lon)
            const localVarPath = `/v1/geo/reverse`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (lat !== undefined) {
                localVarQueryParameter['lat'] = lat;
            }

            if (lon !== undefined) {
                localVarQueryParameter['lon'] = lon;
            }

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GeoApi - functional programming interface
 * @export
 */
export const GeoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GeoApiAxiosParamCreator(configuration)
    return {
        /**
         * Get location address information
         * @summary Get location address information
         * @param {string} authorization Bearer
         * @param {number} lat latitude
         * @param {number} lon longitude
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1GeoReverseGet(authorization: string, lat: number, lon: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GeocodeReverseResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1GeoReverseGet(authorization, lat, lon, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GeoApi.v1GeoReverseGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GeoApi - factory interface
 * @export
 */
export const GeoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GeoApiFp(configuration)
    return {
        /**
         * Get location address information
         * @summary Get location address information
         * @param {string} authorization Bearer
         * @param {number} lat latitude
         * @param {number} lon longitude
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1GeoReverseGet(authorization: string, lat: number, lon: number, options?: any): AxiosPromise<GeocodeReverseResult> {
            return localVarFp.v1GeoReverseGet(authorization, lat, lon, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GeoApi - object-oriented interface
 * @export
 * @class GeoApi
 * @extends {BaseAPI}
 */
export class GeoApi extends BaseAPI {
    /**
     * Get location address information
     * @summary Get location address information
     * @param {string} authorization Bearer
     * @param {number} lat latitude
     * @param {number} lon longitude
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GeoApi
     */
    public v1GeoReverseGet(authorization: string, lat: number, lon: number, options?: RawAxiosRequestConfig) {
        return GeoApiFp(this.configuration).v1GeoReverseGet(authorization, lat, lon, options).then((request) => request(this.axios, this.basePath));
    }
}

