/* tslint:disable */
/* eslint-disable */
/**
 * Expenso-app API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fiber@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AuthGoogleLoginRequest
 */
export interface AuthGoogleLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthGoogleLoginRequest
     */
    'accessToken': string;
}
/**
 * 
 * @export
 * @interface AuthUserLoginResult
 */
export interface AuthUserLoginResult {
    /**
     * 
     * @type {string}
     * @memberof AuthUserLoginResult
     */
    'accessToken': string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserLoginResult
     */
    'sessionToken': string;
    /**
     * 
     * @type {UserUserDto}
     * @memberof AuthUserLoginResult
     */
    'user': UserUserDto;
}
/**
 * 
 * @export
 * @interface ExpensesExpenseDto
 */
export interface ExpensesExpenseDto {
    /**
     * 
     * @type {string}
     * @memberof ExpensesExpenseDto
     */
    'category': string;
    /**
     * 
     * @type {number}
     * @memberof ExpensesExpenseDto
     */
    'createdAt': number;
    /**
     * 
     * @type {string}
     * @memberof ExpensesExpenseDto
     */
    'currencyCode': string;
    /**
     * 
     * @type {Array<ExpensesExpenseItemDto>}
     * @memberof ExpensesExpenseDto
     */
    'details': Array<ExpensesExpenseItemDto>;
    /**
     * 
     * @type {string}
     * @memberof ExpensesExpenseDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ExpensesExpenseDto
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof ExpensesExpenseDto
     */
    'total': number;
    /**
     * 
     * @type {number}
     * @memberof ExpensesExpenseDto
     */
    'updatedAt': number;
    /**
     * 
     * @type {string}
     * @memberof ExpensesExpenseDto
     */
    'userId': string;
}
/**
 * 
 * @export
 * @interface ExpensesExpenseItemDto
 */
export interface ExpensesExpenseItemDto {
    /**
     * 
     * @type {string}
     * @memberof ExpensesExpenseItemDto
     */
    'currencyCode': string;
    /**
     * 
     * @type {string}
     * @memberof ExpensesExpenseItemDto
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof ExpensesExpenseItemDto
     */
    'price': number;
}
/**
 * 
 * @export
 * @interface ExpensesExpenseResult
 */
export interface ExpensesExpenseResult {
    /**
     * 
     * @type {ExpensesExpenseDto}
     * @memberof ExpensesExpenseResult
     */
    'expense': ExpensesExpenseDto;
}
/**
 * 
 * @export
 * @interface ExpensesExpenseUpsertDto
 */
export interface ExpensesExpenseUpsertDto {
    /**
     * 
     * @type {string}
     * @memberof ExpensesExpenseUpsertDto
     */
    'category': string;
    /**
     * 
     * @type {string}
     * @memberof ExpensesExpenseUpsertDto
     */
    'currencyCode': string;
    /**
     * 
     * @type {Array<ExpensesExpenseItemDto>}
     * @memberof ExpensesExpenseUpsertDto
     */
    'details': Array<ExpensesExpenseItemDto>;
    /**
     * 
     * @type {string}
     * @memberof ExpensesExpenseUpsertDto
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof ExpensesExpenseUpsertDto
     */
    'total': number;
}
/**
 * 
 * @export
 * @interface ExpensesExpensesResult
 */
export interface ExpensesExpensesResult {
    /**
     * 
     * @type {Array<ExpensesExpenseDto>}
     * @memberof ExpensesExpensesResult
     */
    'expenses': Array<ExpensesExpenseDto>;
}
/**
 * 
 * @export
 * @interface HelpersErrorResponse
 */
export interface HelpersErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof HelpersErrorResponse
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof HelpersErrorResponse
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface UserUpdateUserDto
 */
export interface UserUpdateUserDto {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateUserDto
     */
    'alias'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateUserDto
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateUserDto
     */
    'lastName'?: string;
    /**
     * 
     * @type {UserUserSettingsDb}
     * @memberof UserUpdateUserDto
     */
    'settings': UserUserSettingsDb;
}
/**
 * 
 * @export
 * @interface UserUserDto
 */
export interface UserUserDto {
    /**
     * 
     * @type {string}
     * @memberof UserUserDto
     */
    'alias'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDto
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDto
     */
    'googleId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDto
     */
    'lastName'?: string;
    /**
     * 
     * @type {UserUserSettingsDto}
     * @memberof UserUserDto
     */
    'settings': UserUserSettingsDto;
}
/**
 * 
 * @export
 * @interface UserUserResult
 */
export interface UserUserResult {
    /**
     * 
     * @type {UserUserDto}
     * @memberof UserUserResult
     */
    'user': UserUserDto;
}
/**
 * 
 * @export
 * @interface UserUserSettingsDb
 */
export interface UserUserSettingsDb {
    /**
     * 
     * @type {string}
     * @memberof UserUserSettingsDb
     */
    'defaultCurrency'?: string;
}
/**
 * 
 * @export
 * @interface UserUserSettingsDto
 */
export interface UserUserSettingsDto {
    /**
     * 
     * @type {string}
     * @memberof UserUserSettingsDto
     */
    'defaultCurrency'?: string;
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Google auth verification
         * @summary Google auth login
         * @param {AuthGoogleLoginRequest} data Google login request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginGoogleAuthPost: async (data: AuthGoogleLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('loginGoogleAuthPost', 'data', data)
            const localVarPath = `/login/google-auth`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * Google auth verification
         * @summary Google auth login
         * @param {AuthGoogleLoginRequest} data Google login request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginGoogleAuthPost(data: AuthGoogleLoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthUserLoginResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginGoogleAuthPost(data, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AuthApi.loginGoogleAuthPost']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * Google auth verification
         * @summary Google auth login
         * @param {AuthGoogleLoginRequest} data Google login request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginGoogleAuthPost(data: AuthGoogleLoginRequest, options?: any): AxiosPromise<AuthUserLoginResult> {
            return localVarFp.loginGoogleAuthPost(data, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * Google auth verification
     * @summary Google auth login
     * @param {AuthGoogleLoginRequest} data Google login request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public loginGoogleAuthPost(data: AuthGoogleLoginRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).loginGoogleAuthPost(data, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ExpensesApi - axios parameter creator
 * @export
 */
export const ExpensesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get expense by expenseId
         * @summary Get expense by expenseId
         * @param {string} authorization Bearer
         * @param {string} expenseId :expenseId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExpensesExpenseIdGet: async (authorization: string, expenseId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('v1ExpensesExpenseIdGet', 'authorization', authorization)
            // verify required parameter 'expenseId' is not null or undefined
            assertParamExists('v1ExpensesExpenseIdGet', 'expenseId', expenseId)
            const localVarPath = `/v1/expenses/:expenseId`
                .replace(`{${"expenseId"}}`, encodeURIComponent(String(expenseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update an expense for a logged in user
         * @summary Update an expense for a logged in user
         * @param {string} authorization Bearer
         * @param {string} expenseId :expenseId
         * @param {ExpensesExpenseUpsertDto} data Update expense model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExpensesExpenseIdPut: async (authorization: string, expenseId: string, data: ExpensesExpenseUpsertDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('v1ExpensesExpenseIdPut', 'authorization', authorization)
            // verify required parameter 'expenseId' is not null or undefined
            assertParamExists('v1ExpensesExpenseIdPut', 'expenseId', expenseId)
            // verify required parameter 'data' is not null or undefined
            assertParamExists('v1ExpensesExpenseIdPut', 'data', data)
            const localVarPath = `/v1/expenses/:expenseId`
                .replace(`{${"expenseId"}}`, encodeURIComponent(String(expenseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get expenses for the logged in user
         * @summary Get expenses for the logged in user
         * @param {string} authorization Bearer
         * @param {number} page page or 1 by default
         * @param {number} pageSize pageSize or 300 by default
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExpensesGet: async (authorization: string, page: number, pageSize: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('v1ExpensesGet', 'authorization', authorization)
            // verify required parameter 'page' is not null or undefined
            assertParamExists('v1ExpensesGet', 'page', page)
            // verify required parameter 'pageSize' is not null or undefined
            assertParamExists('v1ExpensesGet', 'pageSize', pageSize)
            const localVarPath = `/v1/expenses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create an expense for a logged in user
         * @summary Create an expense for a logged in user
         * @param {string} authorization Bearer
         * @param {ExpensesExpenseUpsertDto} data Update expense model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExpensesPost: async (authorization: string, data: ExpensesExpenseUpsertDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('v1ExpensesPost', 'authorization', authorization)
            // verify required parameter 'data' is not null or undefined
            assertParamExists('v1ExpensesPost', 'data', data)
            const localVarPath = `/v1/expenses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExpensesApi - functional programming interface
 * @export
 */
export const ExpensesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExpensesApiAxiosParamCreator(configuration)
    return {
        /**
         * Get expense by expenseId
         * @summary Get expense by expenseId
         * @param {string} authorization Bearer
         * @param {string} expenseId :expenseId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ExpensesExpenseIdGet(authorization: string, expenseId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExpensesExpenseResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ExpensesExpenseIdGet(authorization, expenseId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['ExpensesApi.v1ExpensesExpenseIdGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Update an expense for a logged in user
         * @summary Update an expense for a logged in user
         * @param {string} authorization Bearer
         * @param {string} expenseId :expenseId
         * @param {ExpensesExpenseUpsertDto} data Update expense model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ExpensesExpenseIdPut(authorization: string, expenseId: string, data: ExpensesExpenseUpsertDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExpensesExpenseResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ExpensesExpenseIdPut(authorization, expenseId, data, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['ExpensesApi.v1ExpensesExpenseIdPut']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Get expenses for the logged in user
         * @summary Get expenses for the logged in user
         * @param {string} authorization Bearer
         * @param {number} page page or 1 by default
         * @param {number} pageSize pageSize or 300 by default
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ExpensesGet(authorization: string, page: number, pageSize: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExpensesExpensesResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ExpensesGet(authorization, page, pageSize, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['ExpensesApi.v1ExpensesGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Create an expense for a logged in user
         * @summary Create an expense for a logged in user
         * @param {string} authorization Bearer
         * @param {ExpensesExpenseUpsertDto} data Update expense model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ExpensesPost(authorization: string, data: ExpensesExpenseUpsertDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExpensesExpenseResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ExpensesPost(authorization, data, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['ExpensesApi.v1ExpensesPost']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * ExpensesApi - factory interface
 * @export
 */
export const ExpensesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExpensesApiFp(configuration)
    return {
        /**
         * Get expense by expenseId
         * @summary Get expense by expenseId
         * @param {string} authorization Bearer
         * @param {string} expenseId :expenseId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExpensesExpenseIdGet(authorization: string, expenseId: string, options?: any): AxiosPromise<ExpensesExpenseResult> {
            return localVarFp.v1ExpensesExpenseIdGet(authorization, expenseId, options).then((request) => request(axios, basePath));
        },
        /**
         * Update an expense for a logged in user
         * @summary Update an expense for a logged in user
         * @param {string} authorization Bearer
         * @param {string} expenseId :expenseId
         * @param {ExpensesExpenseUpsertDto} data Update expense model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExpensesExpenseIdPut(authorization: string, expenseId: string, data: ExpensesExpenseUpsertDto, options?: any): AxiosPromise<ExpensesExpenseResult> {
            return localVarFp.v1ExpensesExpenseIdPut(authorization, expenseId, data, options).then((request) => request(axios, basePath));
        },
        /**
         * Get expenses for the logged in user
         * @summary Get expenses for the logged in user
         * @param {string} authorization Bearer
         * @param {number} page page or 1 by default
         * @param {number} pageSize pageSize or 300 by default
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExpensesGet(authorization: string, page: number, pageSize: number, options?: any): AxiosPromise<ExpensesExpensesResult> {
            return localVarFp.v1ExpensesGet(authorization, page, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * Create an expense for a logged in user
         * @summary Create an expense for a logged in user
         * @param {string} authorization Bearer
         * @param {ExpensesExpenseUpsertDto} data Update expense model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExpensesPost(authorization: string, data: ExpensesExpenseUpsertDto, options?: any): AxiosPromise<ExpensesExpenseResult> {
            return localVarFp.v1ExpensesPost(authorization, data, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ExpensesApi - object-oriented interface
 * @export
 * @class ExpensesApi
 * @extends {BaseAPI}
 */
export class ExpensesApi extends BaseAPI {
    /**
     * Get expense by expenseId
     * @summary Get expense by expenseId
     * @param {string} authorization Bearer
     * @param {string} expenseId :expenseId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApi
     */
    public v1ExpensesExpenseIdGet(authorization: string, expenseId: string, options?: RawAxiosRequestConfig) {
        return ExpensesApiFp(this.configuration).v1ExpensesExpenseIdGet(authorization, expenseId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update an expense for a logged in user
     * @summary Update an expense for a logged in user
     * @param {string} authorization Bearer
     * @param {string} expenseId :expenseId
     * @param {ExpensesExpenseUpsertDto} data Update expense model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApi
     */
    public v1ExpensesExpenseIdPut(authorization: string, expenseId: string, data: ExpensesExpenseUpsertDto, options?: RawAxiosRequestConfig) {
        return ExpensesApiFp(this.configuration).v1ExpensesExpenseIdPut(authorization, expenseId, data, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get expenses for the logged in user
     * @summary Get expenses for the logged in user
     * @param {string} authorization Bearer
     * @param {number} page page or 1 by default
     * @param {number} pageSize pageSize or 300 by default
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApi
     */
    public v1ExpensesGet(authorization: string, page: number, pageSize: number, options?: RawAxiosRequestConfig) {
        return ExpensesApiFp(this.configuration).v1ExpensesGet(authorization, page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create an expense for a logged in user
     * @summary Create an expense for a logged in user
     * @param {string} authorization Bearer
     * @param {ExpensesExpenseUpsertDto} data Update expense model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApi
     */
    public v1ExpensesPost(authorization: string, data: ExpensesExpenseUpsertDto, options?: RawAxiosRequestConfig) {
        return ExpensesApiFp(this.configuration).v1ExpensesPost(authorization, data, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get user info
         * @summary Get user info
         * @param {string} authorization Bearer
         * @param {string} userId uuid or me - to get info for the logged in user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1UsersUserIdGet: async (authorization: string, userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('v1UsersUserIdGet', 'authorization', authorization)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('v1UsersUserIdGet', 'userId', userId)
            const localVarPath = `/v1/users/:userId`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update user info
         * @summary Update user info
         * @param {UserUpdateUserDto} data User update data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1UsersUserIdPut: async (data: UserUpdateUserDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('v1UsersUserIdPut', 'data', data)
            const localVarPath = `/v1/users/:userId`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * Get user info
         * @summary Get user info
         * @param {string} authorization Bearer
         * @param {string} userId uuid or me - to get info for the logged in user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1UsersUserIdGet(authorization: string, userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserUserResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1UsersUserIdGet(authorization, userId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['UserApi.v1UsersUserIdGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Update user info
         * @summary Update user info
         * @param {UserUpdateUserDto} data User update data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1UsersUserIdPut(data: UserUpdateUserDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserUserResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1UsersUserIdPut(data, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['UserApi.v1UsersUserIdPut']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * Get user info
         * @summary Get user info
         * @param {string} authorization Bearer
         * @param {string} userId uuid or me - to get info for the logged in user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1UsersUserIdGet(authorization: string, userId: string, options?: any): AxiosPromise<UserUserResult> {
            return localVarFp.v1UsersUserIdGet(authorization, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Update user info
         * @summary Update user info
         * @param {UserUpdateUserDto} data User update data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1UsersUserIdPut(data: UserUpdateUserDto, options?: any): AxiosPromise<UserUserResult> {
            return localVarFp.v1UsersUserIdPut(data, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * Get user info
     * @summary Get user info
     * @param {string} authorization Bearer
     * @param {string} userId uuid or me - to get info for the logged in user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public v1UsersUserIdGet(authorization: string, userId: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).v1UsersUserIdGet(authorization, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update user info
     * @summary Update user info
     * @param {UserUpdateUserDto} data User update data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public v1UsersUserIdPut(data: UserUpdateUserDto, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).v1UsersUserIdPut(data, options).then((request) => request(this.axios, this.basePath));
    }
}



