generatorOptions:
  disableNameSuffixHash: true

namespace: accounts-stage
namePrefix: stage-

secretGenerator:
  - name: accounts-secret
    envs:
      - .env

commonLabels:
  env: stage

resources:
  - ./deployment.accounts-api.yaml
  - ./deployment.accounts-db.yaml
  - ./namespace
  - ./rbac
  - ./roleBinding
  - ./serviceAccount
