generatorOptions:
  disableNameSuffixHash: true

namespace: accounts-stage
namePrefix: stage-

secretGenerator:
  - name: accounts-secret
    envs:
      - .env

commonLabels:
  env: stage

resources:
  - ./accounts-api.deployment
  - ./mongo.deployment
  - ./namespace
  - ./rbac
  - ./roleBinding
  - ./serviceAccount
