---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-role
rules:
  - apiGroups: ['extensions', 'apps']
    resources: ['deployments']
    verbs: ['*']

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: accounts-deployer
automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
metadata:
  name: accounts-deployer-secret
  annotations:
    kubernetes.io/service-account.name: accounts-deployer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-role-binding
subjects:
  - kind: ServiceAccount
    name: accounts-deployer
roleRef:
  kind: Role
  name: deployment-role
  apiGroup: rbac.authorization.k8s.io
