/* tslint:disable */
/* eslint-disable */
/**
 * Expenso-app API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fiber@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserUserSettingsDb } from './user-user-settings-db';

/**
 * 
 * @export
 * @interface UserUpdateUserDto
 */
export interface UserUpdateUserDto {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateUserDto
     */
    'alias'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateUserDto
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateUserDto
     */
    'lastName'?: string;
    /**
     * 
     * @type {UserUserSettingsDb}
     * @memberof UserUpdateUserDto
     */
    'settings': UserUserSettingsDb;
}

