/* tslint:disable */
/* eslint-disable */
/**
 * Accounts API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: aira3t@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Currency } from './currency';

/**
 * 
 * @export
 * @interface AccountDetail
 */
export interface AccountDetail {
    /**
     * 
     * @type {Currency}
     * @memberof AccountDetail
     */
    'currencyCode': Currency;
    /**
     * 
     * @type {string}
     * @memberof AccountDetail
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof AccountDetail
     */
    'value': number;
}



