/* tslint:disable */
/* eslint-disable */
/**
 * Accounts API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: aira3t@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AccountAddress } from './account-address';
// May contain unused imports in some cases
// @ts-ignore
import { AccountCategory } from './account-category';
// May contain unused imports in some cases
// @ts-ignore
import { AccountDetail } from './account-detail';
// May contain unused imports in some cases
// @ts-ignore
import { Currency } from './currency';

/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * 
     * @type {AccountCategory}
     * @memberof Account
     */
    'category': AccountCategory;
    /**
     * 
     * @type {AccountAddress}
     * @memberof Account
     */
    'address': AccountAddress;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    'date': string;
    /**
     * 
     * @type {Currency}
     * @memberof Account
     */
    'currencyCode': Currency;
    /**
     * 
     * @type {Array<AccountDetail>}
     * @memberof Account
     */
    'details': Array<AccountDetail>;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof Account
     */
    'value': number;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    'userId': string;
}



