/* tslint:disable */
/* eslint-disable */
/**
 * Expenso-app API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fiber@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ExpensesExpenseItemDto } from './expenses-expense-item-dto';

/**
 * 
 * @export
 * @interface ExpensesExpenseUpsertDto
 */
export interface ExpensesExpenseUpsertDto {
    /**
     * 
     * @type {string}
     * @memberof ExpensesExpenseUpsertDto
     */
    'category': string;
    /**
     * 
     * @type {string}
     * @memberof ExpensesExpenseUpsertDto
     */
    'currencyCode': string;
    /**
     * 
     * @type {Array<ExpensesExpenseItemDto>}
     * @memberof ExpensesExpenseUpsertDto
     */
    'details': Array<ExpensesExpenseItemDto>;
    /**
     * 
     * @type {string}
     * @memberof ExpensesExpenseUpsertDto
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof ExpensesExpenseUpsertDto
     */
    'total': number;
}

