/* tslint:disable */
/* eslint-disable */
/**
 * Expenso-app API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fiber@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HelpersErrorResponse
 */
export interface HelpersErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof HelpersErrorResponse
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof HelpersErrorResponse
     */
    'message': string;
}

