basePath: /
definitions:
  auth.GoogleLoginRequest:
    properties:
      accessToken:
        type: string
    type: object
  auth.UserLoginResult:
    properties:
      accessToken:
        type: string
      sessionToken:
        type: string
      user:
        $ref: '#/definitions/user.UserDto'
    type: object
  helpers.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  user.UpdateUserDto:
    properties:
      alias:
        type: string
      firstName:
        type: string
      lastName:
        type: string
    type: object
  user.UserDto:
    properties:
      alias:
        type: string
      email:
        type: string
      firstName:
        type: string
      googleId:
        type: string
      id:
        type: string
      lastName:
        type: string
    type: object
  user.UserResult:
    properties:
      user:
        $ref: '#/definitions/user.UserDto'
    type: object
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Expenso-app API
  version: "1.0"
paths:
  /login/google-auth:
    post:
      consumes:
      - application/json
      description: Google auth verification
      parameters:
      - description: Google login request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.GoogleLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.UserLoginResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: Google auth login
      tags:
      - auth
  /v1/users/:userId:
    get:
      description: Get user info
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: Get user info
      tags:
      - user
    put:
      consumes:
      - application/json
      description: Update user info
      parameters:
      - description: User update data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.UpdateUserDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: Update user info
      tags:
      - user
swagger: "2.0"
