/* tslint:disable */
/* eslint-disable */
/**
 * Expenso-app API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fiber@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserUserSettingsDto } from './user-user-settings-dto';

/**
 * 
 * @export
 * @interface UserUserDto
 */
export interface UserUserDto {
    /**
     * 
     * @type {string}
     * @memberof UserUserDto
     */
    'alias'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDto
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDto
     */
    'googleId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDto
     */
    'lastName'?: string;
    /**
     * 
     * @type {UserUserSettingsDto}
     * @memberof UserUserDto
     */
    'settings': UserUserSettingsDto;
}

