name: Run mobile unit test

on:
  pull_request:
    branches: ['main']

jobs:
  run_mobile_unit_tests:
    name: Run mobile unit test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install deps and run tests
        uses: oven-sh/setup-bun@v1
      - run: |
          cd mobile
          bun install
          bun run test
